# Generated by Django 2.1.10 on 2019-10-08 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190813_2114'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'E'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'I'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Category'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
